apiVersion: v1
data:
  mapRoles: |
   - groups:
     - system:masters
     rolearn: arn:aws:iam::171656840418:role/UdacityFlaskDeployCBKubectlRole
     username: build 
   - groups:
     - system:bootstrappers
     - system:nodes
     rolearn: arn:aws:iam::171656840418:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-Y73IAB52O6O8
     username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-27T06:19:02Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-05-27T06:19:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1679"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 8668a2c6-927a-4089-a8b4-264627ec3af5
