apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::171656840418:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::171656840418:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1IHGGXY8B1MNF
      username: system:node:{{EC2PrivateDNSName}}
 mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-26T11:53:16Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-05-26T11:53:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1565"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 0e3efecc-be1e-4a91-9731-bede4d92dcfd
